Repository eclipse-mosaic/mosaic, pull requests merged in 2023-07, with the labels that each got.

#328 cleanup(general): Renamed variable in DatabaseRouting
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/SimulationSimulateStep.java
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/reader/StoppingPlaceReader.java
  lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/DatabaseRouting.java
Labels: clean-up

#329 chore(sumo): Enable compatibility with SUMO version 1.18.0
  Jenkinsfile
  README.md
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java
  test/ci/ci-image-mvn-sumo/Dockerfile
  test/ci/ci-image-mvn-sumo/README.md
Labels: chore

#327 bugfix(sumo): Fix call of adjustToSumoTimeStep
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java
  fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTest.java
  fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTimeStepAdjustmentTest.java
Labels: bugfix

#331 f:ix allow to set a classloader for PackageSpecificTypeAdapter
  lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/gson/PackageSpecificTypeAdapter.java
Labels: bugfix

#335 chore(sumo): Updated validation regex for libsumo version
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java
Labels: chore
