Repository eclipse-mosaic/mosaic, pull requests merged in 2024-08, with the labels that each got.

#399 build: add URL to all poms
  app/tutorials/example-applications/pom.xml
  app/tutorials/highway-management/pom.xml
  app/tutorials/traffic-light-communication/pom.xml
  app/tutorials/weather-warning/pom.xml
  bundle/pom.xml
  fed/mosaic-application/pom.xml
  fed/mosaic-cell/pom.xml
  fed/mosaic-environment/pom.xml
  fed/mosaic-mapping/pom.xml
  fed/mosaic-ns3/pom.xml
  fed/mosaic-omnetpp/pom.xml
  fed/mosaic-output/pom.xml
  fed/mosaic-sns/pom.xml
  fed/mosaic-sumo/pom.xml
  lib/mosaic-communication/pom.xml
  lib/mosaic-database/pom.xml
  lib/mosaic-docker/pom.xml
  lib/mosaic-geomath/pom.xml
  lib/mosaic-interactions/pom.xml
  lib/mosaic-network/pom.xml
  lib/mosaic-objects/pom.xml
  lib/mosaic-routing/pom.xml
  lib/mosaic-utils/pom.xml
  pom.xml
  rti/mosaic-rti-api/pom.xml
  rti/mosaic-rti-core/pom.xml
  rti/mosaic-starter/pom.xml
  test/mosaic-integration-tests/pom.xml
Labels: documentation

#396 feat(rti): pass JVM options to JAVA based federates
  rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java
  rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/WatchDogThread.java
  rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
Labels: enhancement

#402 cleanup: Cleanup Tasks in RTI Code
  rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/parameters/FederateDescriptor.java
  rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
Labels: clean-up

#401 feat(geomath): introduce class for point cloud
  fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/util/TrafficSignManagerTest.java
  lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/PointCloud.java
  lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/spatial/PointCloudTest.java
  lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/PointCloudSerialization.java
  lib/mosaic-utils/src/test/java/org/eclipse/mosaic/lib/util/PointCloudSerializationTest.java
Labels: enhancement
