Repository eclipse-mosaic/mosaic, pull requests merged in 2024-11, with the labels that each got.

#428 feat(sns): support multi-hop unicast for topological and geographical routing
  fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/TransmissionSimulator.java
  fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/AdhocTransmissionModel.java
  fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/SimpleAdhocTransmissionModel.java
  fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/SophisticatedAdhocTransmissionModel.java
  fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/model/AdhocTransmissionModelTest.java
Labels: enhancement, hacktoberfest-accepted

#420 feat: introducing SensorModule to provide access to environmental events
  app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/examples/emergencybrake/EmergencyBrakeApp.java
  app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/SlowDownApp.java
  app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java
  app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassador.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/SimulationKernel.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/AbstractSimulationUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/EnvironmentBasicSensorModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/OperatingSystem.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/modules/Perceptive.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/perception/BasicSensorModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/perception/LidarSensorModule.java
Labels: enhancement, hacktoberfest-accepted

#433 feat: refactor AdHocMessageRoutingBuilder
  app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/examples/emergencybrake/EmergencyBrakeApp.java
  app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/RoadSideUnitApp.java
  app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/VehicleToTrafficLightApp.java
  app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java
  app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/communication/AdHocModule.java
  fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/chain/ChainManagerTest.java
  fed/mosaic-output/src/test/java/org/eclipse/mosaic/fed/output/generator/file/format/InteractionFormatterTest.java
  fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/ambassador/SnsAmbassadorTest.java
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/addressing/AdHocMessageRoutingBuilder.java
  lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/AdHocMessageRoutingBuilderTest.java
  test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendandreceive/SendV2xAppAdHoc.java
  test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendonshutdown/SendOnShutdownApp.java
Labels: enhancement, clean-up

#432 refactor(application): move navigation module interface to api package
  app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/examples/commuter/SimpleCommuterApp.java
  app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java
  app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/RoadSideUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleUnit.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/RoutingNavigationModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/navigation/NavigationModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/navigation/RoutingModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/modules/Navigable.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/modules/Routable.java
  fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/RoutingNavigationModuleTest.java
Labels: clean-up
