Repository eclipse-mosaic/mosaic, pull requests merged in 2024-01, with the labels that each got.

#374 feat(utils): add utility function to move vehicle reference position
  legal/templates/license-header-2024.txt
  lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/VehicleReferenceUtils.java
  pom.xml
  rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicStarter.java
Labels: enhancement

#370 feat: various changes required for ride-hailing
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassador.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/SimulationKernel.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponent.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/INavigationModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/IRoutingModule.java
  fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/NavigationModule.java
  fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassadorTest.java
  fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponentTest.java
  fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/navigation/NavigationModuleTest.java
  fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java
  lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Aggregator.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/VehicleDeparture.java
  lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/DatabaseRouting.java
  lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperRouting.java
  lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/scheduling/Event.java
  test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/mosaicandsumovehicles/SumoVehicle.java
Labels: enhancement, bugfix

#375 fix(v2x): API Change in V2xMessage getPayLoad -> getPayload
  app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/message/GreenWaveMsg.java
  app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/message/InterVehicleMsg.java
  fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleTest.java
  fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/utility/CapacityUtility.java
  fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/chain/SampleV2xMessage.java
  fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/ambassador/SnsAmbassadorTest.java
  lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/GenericV2xMessage.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/V2xMessage.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Cam.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Denm.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Ivim.java
  lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Spatm.java
  lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/CamContentTest.java
  lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/DenmContentTest.java
  lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/IvimContentTest.java
  test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendandreceive/messages/TestMessage.java
  test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendonshutdown/ShutdownMessage.java
Labels: clean-up
